import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Typography from "../Funcss/Components/Typography"
import Container from "../Funcss/Components/Container"
import Breadcrumb from "../Funcss/Components/Breadcrumb"
import Button from "../Funcss/Components/Button"
import Icon from "../Funcss/Components/Icon"
import Card from "../Funcss/Components/Card";
import Input from '../Funcss/Components/Input';
import IconicInput from '../Funcss/Components/IconicInput';
import Div from '../Funcss/Components/Div';
import Section from '../Funcss/Components/Section';
import Grid from '../Funcss/Components/Grid';
import Col from '../Funcss/Components/Col';
import { useState,useEffect } from 'react'

export default function Home() {
  const [email, setemail] = useState("")
  const [password, setpassword] = useState("")
  const Login = ()=>{
 if(email && password){
   sessionStorage.setItem("currentUser" , JSON.stringify(email))
new Promise((resolve,reject)=>{
  localStorage.setItem(email,
    JSON.stringify(
      {
        email:email,
        admin:email == "admin@gmail.com" && password === "12345" ? true : false
      }
    )
    )
resolve("/dashboard") 
}).then(loc=>window.location.assign(loc))
 }else{
   alert("Enter your email and password")
 }
  }
  return (
    <div className="designBg home">
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

     
<Card funcss="width-400-max center white round-edge padding-20 form">
<Div funcss="row-flex">
<div className="padding">
    <Icon icon="fas fa-book" size={3} color="primary" />
</div>
<div className="padding">
<Typography heading="h1" text="Login Account" />
</div>
</Div>
<Grid>
<Col sm={12} md={12} lg={12} funcss="padding">
    <IconicInput funcss="section full-width" position="left" >
    <Icon icon="far fa-paper-plane" color="primary" />
<Input type="email" label="Email" funcss="full-width" bordered={true}  onChange={(e)=>setemail(e.target.value)} />
</IconicInput>
    </Col>
    <Col sm={12} md={12} lg={12} funcss="padding">
    <IconicInput funcss="section full-width" position="left" >
    <Icon icon="fas fa-lock" color="primary" />
<Input type="password" label="Password" funcss="full-width" bordered={true}   onChange={(e)=>setpassword(e.target.value)}/>
</IconicInput>
    </Col>
    <Col sm={12} md={12} lg={12} funcss="padding">
        <Button text="Login" color="white" bg="primary" funcss="full-width"
        onClick={Login}
        />
    </Col>
</Grid>

</Card>


    </div>
  )
}
