import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Typography from "../../Funcss/Components/Typography"
import Container from "../../Funcss/Components/Container"
import Breadcrumb from "../../Funcss/Components/Breadcrumb"
import Button from "../../Funcss/Components/Button"
import Icon from "../../Funcss/Components/Icon"
import Card from "../../Funcss/Components/Card";
import Input from '../../Funcss/Components/Input';
import IconicInput from '../../Funcss/Components/IconicInput';
import Div from '../../Funcss/Components/Div';
import Section from '../../Funcss/Components/Section';
import Grid from '../../Funcss/Components/Grid';
import Col from '../../Funcss/Components/Col';
import Navbar from './../navBar';
import { useState,useEffect } from 'react'


export default function Book() {
    const [category, setcategory] = useState("")
    const [categories, setcategories] = useState([])
    useEffect(() => {
        if(localStorage.getItem("categories")){
            setcategories(
            JSON.parse(
                localStorage.getItem("categories")
            )
            )
        }
    },[])
    
const HandleCategory = ()=>{
if(category){
    categories.push(
        {
            category:category
        }
    )
new Promise((resolve,reject)=>{
localStorage.setItem("categories",
    JSON.stringify(categories)
)
    resolve()
}).then(()=>{window.location.assign("/books")})
}else{
    alert("What is the name of your category.")
}
}
  return (
    <div className="bgHome">
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
<Navbar />
   <div className="main">
      
<Card funcss="width-600-max center white round-edge padding-20 form">
<Div funcss="row-flex padding">
<div className="padding">
    <Icon icon="icon-notebook" size={3} color="primary" />
</div>
<div className="padding">
<Typography heading="h1" text="New Book" />
</div>
</Div>

    <IconicInput funcss="section full-width" position="left" >
    <Icon icon="icon-notebook" color="primary" />
<Input type="text" label="What is your category name?" funcss="full-width" bordered={true} onChange={(e)=>setcategory(e.target.value)} />
</IconicInput>
<p>
<Button text="Add Book" color="white" bg="primary" funcss="full-width"
        onClick={HandleCategory}
        />
</p>
</Card>

   </div>

    </div>
  )
}
